package com.restai.controller;

import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.Resource;
import org.springframework.core.io.UrlResource;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;

import com.restai.common.ControllerUtils;
import com.restai.common.Utils;
import com.restai.repositories.ImageRepository;
// import com.restai.entity.ImageMetadataNOTUSED;
import com.restai.services.RequestForwardService;

@RestController
@RequestMapping("/ai")
public class ImageAIController {
	private final RequestForwardService reqFwdService;
    private static final Logger logger = LoggerFactory.getLogger(ImageAIController.class);
    
    @Value("${app.prompt-dir}")
	private String prompt_dir;
	
	@Value("${app.prompt-output-file}")
	private String prompt_response_file;
	
	@Value("${app.prompt-query}") 
	private String prompt_query;
	
    @Autowired
    private ImageRepository imageRepository;
	// public record ChatResponse(String pythonResult,List<ImageMetadataNOTUSED> history) {}

    public ImageAIController( RequestForwardService reqFwdService, ImageRepository imageRepository) {
        this.reqFwdService = reqFwdService; 
        this.imageRepository = imageRepository;
    }

   
    @PostMapping("/askWithFiles")
    @PreAuthorize("hasRole('USER')") // Only users with 'ROLE_USER' can upload
    public ResponseEntity<Resource>  uploadFiles( @RequestParam("files") MultipartFile[] files, @RequestParam(name = "query", required = false) String query_message ) {
    	String username = SecurityContextHolder.getContext().getAuthentication().getName();
    	logger.debug( "Logged in user "+username+" is making a request to /askWithFiles with message: " + query_message);
    	ControllerUtils controllerUtils = new ControllerUtils();
    	if (files == null || files.length == 0) {
             logger.debug( "No files selected.");
         }
    	 if(files.length > 0) {
			 logger.debug("Received " + files.length + " files for user: " + username);		 
	    	 try {
	    	 String userDirPathString = controllerUtils.createUniqueDirectoryAndSetPermissions(username, prompt_dir,prompt_response_file );
	         // Logic to save each file into the directory created by your Filter
	    	 controllerUtils.uploadFiles(files, userDirPathString);
	    	 String outputFilePath = Utils.resolvePath(userDirPathString, Utils.RESPONSE_PROMPT_FILE);
	         // File file = new File(outputFilePath);
	         String message = query_message != null ? prompt_query.concat(query_message) : prompt_query; 
	         String pythonResultString = reqFwdService.getResultByFastAPI(message, userDirPathString);
	         logger.debug("Python result string is ::"+pythonResultString);
	         Path path = Paths.get(outputFilePath);
	         if(path == null || !Files.exists(path)) {
				 logger.error("Python finished but output file missing: " + outputFilePath);
				 return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
			 }
	         Resource resource = new UrlResource(path.toUri());
	         return controllerUtils.handleFileResponse(resource, "No response generated by Python for user: " + username, imageRepository);
	     } catch (MalformedURLException  e) {
	      		return controllerUtils.handleExceptionResponse( "Malformed URL for output file. User: " + username+ " - " + e.getMessage());		
	     }catch (IOException e) {
	         // Exception Case: General errors (e.g., FastAPI service down)
	    	 return controllerUtils.handleExceptionResponse( "IOException URL for output file. User: " + username+ " - " + e.getMessage());
	     } catch (Exception e) {
	         // Exception Case: General errors (e.g., FastAPI service down)
	    	 return controllerUtils.handleExceptionResponse( "Exception URL for output file. User: " + username+ " - " + e.getMessage());
	     }
    }else {
		 	logger.debug("No files received in the request for user: " + username);
    		try {
				return controllerUtils.handleFileResponse(null, "No response generated by Python for user: " + username, imageRepository);
			} catch (IOException e) {
				logger.error("No files received in the request for user:" );
			}
    		// All other exceptions are handled in the catch block, so we can return a generic error response here
    		return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
		}
    }
    
    
}
