spring.application.name=spring-boot-ai-fashion
app.prompt-dir=${APP_PROMPT_DIR:/default/path}
#src/main/resources/prompt.properties/prompt_files
app.prompt-output-file=${APP_PROMPT_RESPONSE:output_response.json}
app.prompt-query=${API_PROMPT_HARDOCDED:What is in this picture?}
# Maps to the environment variables defined in docker-compose.yml
fastapi.base-url=${FASTAPI_URL:http://localhost:8000}
shared.data.path=${DATA_PATH:/data}

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

# Max size per file
spring.servlet.multipart.max-file-size=10MB
# Max size for the entire request (multiple files)
spring.servlet.multipart.max-request-size=10MB

logging.structured.format.file=ecs
logging.file.name=/app/logs/combined.log
# Match your FastAPI format
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [Spring] - %logger{36} - %-5level - %msg%n
# Set rotation to match (5MB, 5 backups)
logging.logback.rollingpolicy.max-file-size=5MB
logging.logback.rollingpolicy.max-history=5
logging.level.org.springframework.ai=DEBUG
logging.level.com.restai=DEBUG

# Secret must be at least 32 characters (256-bit)
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# 86400000 ms = 24 hours
application.security.jwt.expiration=86400000
# Database connection settings

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.sql.init.mode=always

# Essential Postgres settings
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
