CREATE TABLE  IF NOT EXISTS image_metadata (
    id BIGSERIAL PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    uploaded_by VARCHAR(255),
    file_category VARCHAR(255),
    model_provider VARCHAR(255),
    model_name VARCHAR(255),
    file_created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    file_data BYTEA -- Binary data for the image
);

CREATE TABLE  IF NOT EXISTS user_details (
    user_id VARCHAR(255) PRIMARY KEY DEFAULT gen_random_uuid(),
    username VARCHAR(255) UNIQUE NOT NULL,
    user_email VARCHAR(255),
    address VARCHAR(255),
    country VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP    
);

/* This table is autogenerated with image_data, so we can use it to store tags for each image.
 The image_id is a foreign key referencing the id in the image_metadata table.
  When an image is deleted from the image_metadata table, all associated tags in the image_tags table will also be deleted
   due to the ON DELETE CASCADE constraint. This ensures data integrity and prevents orphaned records in the image_tags table.
CREATE TABLE image_tags (
    image_id BIGINT NOT NULL,
    tag VARCHAR(255),
    CONSTRAINT fk_image_metadata FOREIGN KEY (image_id) REFERENCES image_metadata (id) ON DELETE CASCADE
);
*/

CREATE TABLE IF NOT EXISTS garment (
    id SERIAL PRIMARY KEY,
    content TEXT,
    tags tsvector
);
